/** Animation states of an enemy: activity and view direction (34 = three-quarter view). */
export enum EnemyState {
  IdleFront,
  IdleLeft,
  IdleRight,
  Idle34FrontLeft,
  Idle34FrontRight,
  Idle34BackLeft,
  Idle34BackRight,
  IdleBack,
  WalkFront,
  WalkLeft,
  WalkRight,
  Walk34FrontLeft,
  Walk34FrontRight,
  Walk34BackLeft,
  Walk34BackRight,
  WalkBack,
  ShootingFront,
  Shooting34FrontLeft,
  Shooting34FrontRight,
  Dead,
}