import { LevelData } from '../LevelData'

/** Second, larger level, converted from the former ASCII format. */
export const LEVEL_2: LevelData = {
  objects: [
    // Floor: top at y = 0
    { type: 'block', tile: 'floor', position: { x: 30, y: -0.5, z: 30 }, size: { x: 60, y: 1, z: 60 } },
    // Walls
    { type: 'block', tile: 'brick', position: { x: 30, y: 1.5, z: 0.5 }, size: { x: 60, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 0.5, y: 1.5, z: 30.5 }, size: { x: 1, y: 3, z: 59 } },
    { type: 'block', tile: 'brick', position: { x: 29.5, y: 1.5, z: 7.5 }, size: { x: 1, y: 3, z: 13 } },
    { type: 'block', tile: 'brick', position: { x: 59.5, y: 1.5, z: 30.5 }, size: { x: 1, y: 3, z: 59 } },
    { type: 'block', tile: 'brick', position: { x: 50.5, y: 1.5, z: 4.5 }, size: { x: 5, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 55.5, y: 1.5, z: 5.5 }, size: { x: 7, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 9, y: 1.5, z: 9.5 }, size: { x: 16, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 41.5, y: 1.5, z: 13 }, size: { x: 1, y: 3, z: 6 } },
    { type: 'block', tile: 'brick', position: { x: 24, y: 1.5, z: 13.5 }, size: { x: 10, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 42.5, y: 1.5, z: 18.5 }, size: { x: 1, y: 3, z: 7 } },
    { type: 'block', tile: 'brick', position: { x: 15.5, y: 1.5, z: 21 }, size: { x: 1, y: 3, z: 8 } },
    { type: 'block', tile: 'brick', position: { x: 51, y: 1.5, z: 21.5 }, size: { x: 16, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 11.5, y: 1.5, z: 24.5 }, size: { x: 7, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 8.5, y: 1.5, z: 28 }, size: { x: 1, y: 3, z: 6 } },
    { type: 'block', tile: 'brick', position: { x: 45.5, y: 1.5, z: 26.5 }, size: { x: 5, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 33, y: 1.5, z: 27.5 }, size: { x: 8, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 47.5, y: 1.5, z: 28 }, size: { x: 1, y: 3, z: 2 } },
    { type: 'block', tile: 'brick', position: { x: 36.5, y: 1.5, z: 32 }, size: { x: 1, y: 3, z: 8 } },
    { type: 'block', tile: 'brick', position: { x: 50.5, y: 1.5, z: 28.5 }, size: { x: 5, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 52.5, y: 1.5, z: 32 }, size: { x: 1, y: 3, z: 6 } },
    { type: 'block', tile: 'brick', position: { x: 4.5, y: 1.5, z: 30.5 }, size: { x: 7, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 12, y: 1.5, z: 30.5 }, size: { x: 6, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 14.5, y: 1.5, z: 34 }, size: { x: 1, y: 3, z: 6 } },
    { type: 'block', tile: 'brick', position: { x: 47.5, y: 1.5, z: 34.5 }, size: { x: 9, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 56, y: 1.5, z: 34.5 }, size: { x: 6, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 40.5, y: 1.5, z: 35.5 }, size: { x: 7, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 19, y: 1.5, z: 36.5 }, size: { x: 8, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 43.5, y: 1.5, z: 38.5 }, size: { x: 1, y: 3, z: 5 } },
    { type: 'block', tile: 'brick', position: { x: 22.5, y: 1.5, z: 38.5 }, size: { x: 1, y: 3, z: 3 } },
    { type: 'block', tile: 'brick', position: { x: 22, y: 1.5, z: 46.5 }, size: { x: 22, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 42.5, y: 1.5, z: 46.5 }, size: { x: 3, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 32.5, y: 1.5, z: 53.5 }, size: { x: 1, y: 3, z: 13 } },
    { type: 'block', tile: 'brick', position: { x: 46.5, y: 1.5, z: 47.5 }, size: { x: 7, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 49.5, y: 1.5, z: 54 }, size: { x: 1, y: 3, z: 12 } },
    { type: 'block', tile: 'brick', position: { x: 16.5, y: 1.5, z: 59.5 }, size: { x: 31, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 41, y: 1.5, z: 59.5 }, size: { x: 16, y: 3, z: 1 } },
    { type: 'block', tile: 'brick', position: { x: 54.5, y: 1.5, z: 59.5 }, size: { x: 9, y: 3, z: 1 } },
    // Spawns
    { type: 'player', position: { x: 9.5, y: 0, z: 3.5 } },
    { type: 'enemy', position: { x: 55.5, y: 0, z: 4.5 } },
    { type: 'enemy', position: { x: 24.5, y: 0, z: 10.5 } },
    { type: 'enemy', position: { x: 48.5, y: 0, z: 10.5 } },
    { type: 'enemy', position: { x: 11.5, y: 0, z: 15.5 } },
    { type: 'enemy', position: { x: 38.5, y: 0, z: 15.5 } },
    { type: 'enemy', position: { x: 22.5, y: 0, z: 17.5 } },
    { type: 'enemy', position: { x: 12.5, y: 0, z: 21.5 } },
    { type: 'enemy', position: { x: 31.5, y: 0, z: 22.5 } },
    { type: 'enemy', position: { x: 18.5, y: 0, z: 26.5 } },
    { type: 'enemy', position: { x: 43.5, y: 0, z: 29.5 } },
    { type: 'enemy', position: { x: 7.5, y: 0, z: 36.5 } },
    { type: 'enemy', position: { x: 30.5, y: 0, z: 37.5 } },
    { type: 'enemy', position: { x: 11.5, y: 0, z: 41.5 } },
    { type: 'enemy', position: { x: 35.5, y: 0, z: 44.5 } },
    { type: 'enemy', position: { x: 55.5, y: 0, z: 47.5 } },
    { type: 'enemy', position: { x: 23.5, y: 0, z: 49.5 } },
    { type: 'enemy', position: { x: 39.5, y: 0, z: 51.5 } },
    { type: 'enemy', position: { x: 9.5, y: 0, z: 52.5 } },
    { type: 'enemy', position: { x: 25.5, y: 0, z: 53.5 } },
  ],
}
